name: mind
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.9.3
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - click=8.0.1
  - colorama=0.4.4
  - cryptography=3.4.7
  - cssselect=1.1.0
  - feedfinder2=0.0.4
  - feedparser=6.0.8
  - filelock=3.0.12
  - freetype=2.10.4
  - googledrivedownloader=0.4
  - idna=3.2
  - jbig=2.1
  - jieba3k=0.35.1
  - joblib=1.0.1
  - jpeg=9d
  - lcms2=2.12
  - lerc=2.2.1
  - libdeflate=1.7
  - libiconv=1.16
  - libpng=1.6.37
  - libtiff=4.3.0
  - libxml2=2.9.12
  - libxslt=1.1.33
  - lxml=4.6.3
  - lz4-c=1.9.3
  - newspaper3k=0.2.8
  - nltk=3.6.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pillow=8.3.1
  - pip=21.2.4
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyyaml=5.4.1
  - regex=2021.8.28
  - requests=2.26.0
  - requests-file=1.5.1
  - setuptools=52.0.0
  - sgmllib3k=1.0.0
  - six=1.16.0
  - soupsieve=2.0.1
  - sqlite=3.36.0
  - tk=8.6.11
  - tldextract=3.1.1
  - tqdm=4.62.2
  - tzdata=2021a
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.5.0

